# default settings

DEFAULT_ROWS = 4
DEFAULT_COLS = 4
DEFAULT_TIMEOUT = 60

CARD_FONT_SIZE = 28
BG_COLOR = "#1E1E2E"
TEXT_COLOR = "#FFFFFF"
BUTTON_COLOR = "#4A90D9"

CARD_BACK_COLOR  = "#4A90D9"
CARD_FRONT_COLOR = "#FFFFFF"
CARD_MATCHED_COLOR = "#A8D8A8"

TIMER_NORMAL_COLOR  = "#A8D8A8"
TIMER_WARNING_COLOR = "#FFD700"
TIMER_DANGER_COLOR  = "#FF6B6B"
